module.exports = {
	UPDATE_NAME: 'UPDATE_NAME',
	GET_USERS: 'GET_USERS',
	GET_USERS_FULFILLED: 'GET_USERS_FULFILLED',
	GET_USERS_PENDING: 'GET_USERS_PENDING',
	GET_PROFILE_DETAILS: 'GET_PROFILE_DETAILS',
	GET_PROFILE_DETAILS_PENDING: 'GET_PROFILE_DETAILS_PENDING',
	GET_PROFILE_DETAILS_FULFILLED: 'GET_PROFILE_DETAILS_FULFILLED',
	DEFAULT: 'default',
	LIGHT: 'light',
	DARK: 'dark'
}